spring:
    cloud:
        gateway:
            routes:
                -   id: auth-service
                    predicates:
                        - Path=/auth/login
                    uri: lb://AUTH-SERVICE
                    filters:
                        - RewritePath=/auth/(?<segment>.*), /$\{segment}

                -   id: api-service
                    predicates:
                        - Path=/api/users
                        - Method=POST
                    uri: lb://API-SERVICE
                    filters:
                        - RewritePath=/api/(?<segment>.*), /$\{segment}

                -   id: api-service-with-auth
                    predicates:
                        - Path=/api/**
                    uri: lb://API-SERVICE
                    filters:
                        - RewritePath=/api/(?<segment>.*), /$\{segment}
                        -   name: JwtAuthenticationFilter
                            args:
                                secretKey: ${jwt.secret.key}
